### ISSUE TITLE
Establishing the socket connection within the Landing page

### ISSUE THREAD

**Issue by AhmedSafi97** [AhmedSafi97/mern-chatting-app#29]
https://github.com/AhmedSafi97/chatapp/blob/baec9b3ceb1c05e658451ea4056338650e682189/client/src/Components/ChattingRoom.js#L8-L10

Socket Connection should be established in the landing page and  joining a room will be within the ChattingRoom component

**Comment by varun2india89** [comment]
is this one man built chat script? Do you think that I can contribute to this project in someway ?

**Comment by AhmedSafi97** [comment]
@varun2india89 yes, I've working on this project to learn the MERN stack. you can contribute by opening a pull request but if you have major changes open an issue first and we will discuss it first :smile:

**Comment by terryfu33** [comment]
Hi Ahmed, I have been using your app to learn MERN and it found it very helpful. However, after running my version, my app has 0 rooms. I was wondering if you created rooms within the code, or through MongoDB, and if possible could you show me code examples of how you did so.
Thanks!
