### ISSUE TITLE
GET http://localhost:8080/socket.io/?EIO=4&transport=polling&t=NZaTRkz 404 (Not Found) 

### ISSUE THREAD

**Issue by 2sajib2** [AhmedSafi97/mern-chatting-app#56]
hey mate, I am new at socket.io, I just copied all of your message part code tried to implement it in my existing code, but I am getting the above error, did you know to solve this!
I really need to solve this, I have been stuck here for a long time now,

**Comment by AhmedSafi97** [comment]
@2sajib2  Hi there, 
Thanks for pointing this out, it doesn't work locally for me too. I'll try to solve this out and will let you know back then.
